/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;
import DAO.AddboletoDAO;
import DTO.AddboletoDTO;
import javax.swing.JButton;
import javax.swing.JOptionPane;
/**
 *
 * @author rodri
 */
public class Adicionarboleto extends javax.swing.JFrame {

    


    
 
    public Adicionarboleto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        varfix = new javax.swing.ButtonGroup();
        lucrodespe = new javax.swing.ButtonGroup();
        vistparcela = new javax.swing.ButtonGroup();
        Bottfixa = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        Bottdespesas = new javax.swing.JCheckBox();
        Cituaciones = new javax.swing.JComboBox<>();
        Bottlucro = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Datadepagament = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        desctxt = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Bottvaria = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        avista = new javax.swing.JCheckBox();
        Parcela = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Confirmasenha = new javax.swing.JTextField();
        valo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        varfix.add(Bottfixa);
        Bottfixa.setText("Fixa");
        Bottfixa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BottfixaItemStateChanged(evt);
            }
        });
        Bottfixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottfixaActionPerformed(evt);
            }
        });
        getContentPane().add(Bottfixa);
        Bottfixa.setBounds(82, 60, 80, 15);

        jLabel4.setText("Tipo:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(12, 65, 58, 15);

        lucrodespe.add(Bottdespesas);
        Bottdespesas.setText("Despesas");
        Bottdespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottdespesasActionPerformed(evt);
            }
        });
        getContentPane().add(Bottdespesas);
        Bottdespesas.setBounds(80, 30, 100, 23);

        Cituaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paga", "Atrasada" }));
        Cituaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CituacionesActionPerformed(evt);
            }
        });
        getContentPane().add(Cituaciones);
        Cituaciones.setBounds(140, 120, 116, 24);

        lucrodespe.add(Bottlucro);
        Bottlucro.setText("Lucro");
        Bottlucro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottlucroActionPerformed(evt);
            }
        });
        getContentPane().add(Bottlucro);
        Bottlucro.setBounds(180, 30, 70, 23);

        jLabel2.setText("Situaçao:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 122, 80, 15);

        jLabel5.setText("Adicionar:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(12, 39, 60, 15);

        try {
            Datadepagament.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Datadepagament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatadepagamentActionPerformed(evt);
            }
        });
        getContentPane().add(Datadepagament);
        Datadepagament.setBounds(140, 90, 116, 19);

        desctxt.setColumns(20);
        desctxt.setRows(5);
        jScrollPane1.setViewportView(desctxt);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(277, 61, 218, 135);

        jLabel6.setText("Data do pagamento");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 90, 120, 15);

        jLabel3.setText("Descriçao:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(277, 39, 120, 15);

        varfix.add(Bottvaria);
        Bottvaria.setText("Variavel");
        getContentPane().add(Bottvaria);
        Bottvaria.setBounds(170, 60, 80, 22);

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(440, 220, 80, 25);

        jLabel1.setText("Valor:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 147, 60, 15);

        jLabel7.setText("Forma de pagamento");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(12, 184, 130, 15);

        vistparcela.add(avista);
        avista.setText("Ávista");
        avista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avistaActionPerformed(evt);
            }
        });
        getContentPane().add(avista);
        avista.setBounds(12, 207, 70, 23);

        vistparcela.add(Parcela);
        Parcela.setText("Parcelado");
        getContentPane().add(Parcela);
        Parcela.setBounds(80, 210, 80, 23);

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 220, 80, 25);

        jLabel9.setText("sua senha");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(260, 200, 70, 15);

        Confirmasenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmasenhaActionPerformed(evt);
            }
        });
        getContentPane().add(Confirmasenha);
        Confirmasenha.setBounds(250, 220, 90, 25);

        valo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valoActionPerformed(evt);
            }
        });
        getContentPane().add(valo);
        valo.setBounds(140, 150, 116, 19);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\rodri\\Documents\\conectadojavacql\\a62cfd8bdc98858b1ff7f0503d54b1d9.jpg")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, -70, 870, 680);

        setSize(new java.awt.Dimension(541, 322));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CituacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CituacionesActionPerformed
       //colocar a acao aqui
    }//GEN-LAST:event_CituacionesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(Inteface.adm==true){ 
        TelaAdm telapc = new TelaAdm();
        telapc.setVisible(true);
        dispose();
       } else{
          Telauzer u=new Telauzer();
          u.setVisible(true);
          dispose();
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String lucro_despesa;//jass
        String fixa_var;//jass
        String data;//jass
        String situacao;//jazz
        String descricao;//jass
        String forma;//jazz
        int parceladas;
        String password;
        
        
        descricao=desctxt.getText();
        double value=Double.parseDouble(valo.getText());
        data=Datadepagament.getText();
        password=Confirmasenha.getText();
              
        
        
         AddboletoDTO objaddboleto=new AddboletoDTO();
         objaddboleto.setValor(value);
         objaddboleto.setDescricao(descricao);
         objaddboleto.setVencimento(data);
         objaddboleto.setConfirmasenha(password);
            if(Bottfixa.isSelected()){
             objaddboleto.setFixa_var("conta Fixa");
            }
            if(Bottvaria.isSelected()){
            objaddboleto.setFixa_var("conta Variavel");
            }
            if(Bottdespesas.isSelected()){
            objaddboleto.setLucro_despesa("Despesas");
            }
            if(Bottlucro.isSelected()){
            objaddboleto.setLucro_despesa("lucro");
            }
            if(Cituaciones.getSelectedItem().toString().equals("Paga")){
                objaddboleto.setPag_vanc("conta paga");
            }
            if(Cituaciones.getSelectedItem().toString().equals("Atrasada")){
                objaddboleto.setPag_vanc("conta atrasada");
            }
            if(Parcela.isSelected()){
            objaddboleto.setParcelado_avista("conta parcelada");
            }
            if(avista.isSelected()){
            objaddboleto.setParcelado_avista("conta Avista");
            }
            
            
            
              
         AddboletoDAO Cadastroboleto=new AddboletoDAO();
         Cadastroboleto.Cadastroboleto(objaddboleto);
                        
        
        //forma= Adddespesas.getText();
        //lucro_despesa=lucrodespe.getButtonCount();
        JOptionPane.showMessageDialog(null, "cadastro concluido com sucesso");
        valo.setText("");
        desctxt.setText("");
        Datadepagament.setText("");
        Confirmasenha.setText("");
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ConfirmasenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmasenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmasenhaActionPerformed

    private void avistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avistaActionPerformed
        // colocar a o codigo que vai escolher a ação
    }//GEN-LAST:event_avistaActionPerformed

    private void BottfixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottfixaActionPerformed
       
        
// colocar o codigo que for fazer a escolha da opção
    }//GEN-LAST:event_BottfixaActionPerformed

    private void BottdespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottdespesasActionPerformed

    }//GEN-LAST:event_BottdespesasActionPerformed

    private void BottlucroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottlucroActionPerformed

    }//GEN-LAST:event_BottlucroActionPerformed

    private void BottfixaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BottfixaItemStateChanged
       String tipo=("Conta Fixa");
       
    }//GEN-LAST:event_BottfixaItemStateChanged

    private void DatadepagamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatadepagamentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DatadepagamentActionPerformed

    private void valoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        java.awt.EventQueue.invokeLater(() -> {
            new Adicionarboleto().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Bottdespesas;
    private javax.swing.JCheckBox Bottfixa;
    private javax.swing.JCheckBox Bottlucro;
    private javax.swing.JCheckBox Bottvaria;
    private javax.swing.JComboBox<String> Cituaciones;
    private javax.swing.JTextField Confirmasenha;
    private javax.swing.JFormattedTextField Datadepagament;
    private javax.swing.JCheckBox Parcela;
    private javax.swing.JCheckBox avista;
    private javax.swing.JTextArea desctxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup lucrodespe;
    private javax.swing.JTextField valo;
    private javax.swing.ButtonGroup varfix;
    private javax.swing.ButtonGroup vistparcela;
    // End of variables declaration//GEN-END:variables
}
