/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.AddusuarioDAO;
import DTO.Addnewusuario;
import javax.swing.JOptionPane;

/**
 *
 * @author rodri
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nomenovo = new javax.swing.JTextField();
        senha = new javax.swing.JPasswordField();
        confirmasenha = new javax.swing.JPasswordField();
        telefone = new javax.swing.JFormattedTextField();
        confirmaemail = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        nick = new javax.swing.JTextField();
        datadenascimento = new javax.swing.JFormattedTextField();
        nacionalidade = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("CADASTRO DE NOVOS USUARIOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(139, 26, 303, 23);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Nome");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 80, 40, 19);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Telefone");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 120, 70, 19);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 150, 70, 19);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("confirmaçao de Email");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 180, 160, 19);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Data de Nacimento");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(286, 111, 140, 19);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Nacionalidade");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(293, 136, 110, 19);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Nick do usuario");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 210, 110, 19);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Senha");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 240, 60, 19);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Confrimaçao da Senha ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 260, 170, 19);

        nomenovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomenovoActionPerformed(evt);
            }
        });
        getContentPane().add(nomenovo);
        nomenovo.setBounds(100, 80, 170, 19);
        getContentPane().add(senha);
        senha.setBounds(100, 240, 170, 19);
        getContentPane().add(confirmasenha);
        confirmasenha.setBounds(160, 260, 110, 19);

        try {
            telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(telefone);
        telefone.setBounds(100, 120, 170, 19);
        getContentPane().add(confirmaemail);
        confirmaemail.setBounds(160, 180, 110, 19);
        getContentPane().add(email);
        email.setBounds(100, 150, 170, 19);
        getContentPane().add(nick);
        nick.setBounds(140, 210, 130, 19);

        try {
            datadenascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(datadenascimento);
        datadenascimento.setBounds(428, 109, 146, 19);
        getContentPane().add(nacionalidade);
        nacionalidade.setBounds(428, 134, 146, 19);

        jButton1.setText("CADASTRA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(146, 297, 163, 25);

        jButton2.setText("VOLTAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(351, 297, 153, 25);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\rodri\\Documents\\conectadojavacql\\a62cfd8bdc98858b1ff7f0503d54b1d9.jpg")); // NOI18N
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 80, 590, 340);

        setSize(new java.awt.Dimension(612, 421));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomenovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomenovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomenovoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nome;
        String gmail, email1;
        String nic;
        String senh, senha1;
        String nascim;
        String naciona;
        String fone;
        
        nome=nomenovo.getText();
        fone=telefone.getText();
        gmail=email.getText();
        email1=confirmaemail.getText();
        nic=nick.getText();
        senh=senha.getText();
        senha1=confirmasenha.getText();
        nascim=datadenascimento.getText();
        naciona=nacionalidade.getText();
        
        if (nomenovo.getText().isEmpty() && email.getText().isEmpty() && nick.getText().isEmpty() && senha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "preencha todos os campos");
            return;
        }
        else if(senh.equals(senha1)&& gmail.equals(email1))
        {
            Addnewusuario objadduser=new Addnewusuario();
            objadduser.setNome(nome);
            objadduser.setTelefone(fone);
            objadduser.setEmail(gmail); 
            objadduser.setNick(nic);
            objadduser.setSenha(senh);
            objadduser.setNascimento(nascim);
            objadduser.setNascionalidade(naciona);
           
            
            AddusuarioDAO objaddDAO=new AddusuarioDAO();
            objaddDAO.Cadastrouser(objadduser);
            
            JOptionPane.showMessageDialog(null, "cadastro concluido com sucesso");
            
            
            
         nomenovo.setText("");
        telefone.setText("");
        email.setText("");
        confirmaemail.setText("");
        nick.setText("");
        senha.setText("");
        confirmasenha.setText("");
        datadenascimento.setText("");
        nacionalidade.setText("");
            
          
        }
         else{
            JOptionPane.showMessageDialog(null, "senha ou email nao sao iguais");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Inteface.adm=false; 
        TelaAdm telapc = new TelaAdm();
        telapc.setVisible(true);
        dispose();
                
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField confirmaemail;
    private javax.swing.JPasswordField confirmasenha;
    private javax.swing.JFormattedTextField datadenascimento;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nacionalidade;
    private javax.swing.JTextField nick;
    private javax.swing.JTextField nomenovo;
    private javax.swing.JPasswordField senha;
    private javax.swing.JFormattedTextField telefone;
    // End of variables declaration//GEN-END:variables
}
